apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "processor.fullname" . }}
  labels:
    {{- include "processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processor.replicaCount }}
  selector:
    matchLabels:
      {{- include "processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "processor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.processor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.processor.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "processor.fullname" . }}
          securityContext:
            {{- toYaml .Values.processor.securityContext | nindent 12 }}
          image: "{{ .Values.processor.image.repository }}/{{ .Values.processor.image.name }}:{{ .Values.processor.image.tag }}"
          imagePullPolicy: {{ .Values.processor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.processor.container.internalPort }}
              protocol: TCP
          {{- if .Values.processor.container.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.processor.container.livenessProbe.path }}"
              port: {{ .Values.processor.container.livenessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.processor.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.processor.container.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.processor.container.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.processor.container.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.processor.container.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.processor.container.readinessProbe.path }}"
              port: {{ .Values.processor.container.readinessProbe.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.processor.container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.processor.container.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.processor.container.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.processor.container.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.processor.container.readinessProbe.failureThreshold }}
          {{- end }}
          env:
            - name: APP_TYPE
              value: processor
            - name: ARCHIVE_URL
              value: http://{{ include "archiveGateway.fullname" . }}:{{ .Values.archiveGateway.service.port }}/graphql
          envFrom:
          - configMapRef:
              name: node-indexer-configmap
          - configMapRef:
              name: {{ .Release.Name }}-version
          - secretRef:
              name: indexer-db-secret
          resources:
            {{- toYaml .Values.processor.resources | nindent 12 }}
      {{- with .Values.processor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.processor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.processor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
